import React from 'react';
import { Strategy, Filter } from './types';
import { 
    Compass, Heart, Square, Trophy, Zap, Cloud, Frown, 
    Activity, Theater, FrownIcon, CloudIcon, Angry, Droplets, 
    MessageSquare, DoorOpen, Utensils, Ghost, VolumeX, RotateCcw, 
    Power
} from 'lucide-react';

// Función para crear iconos con estilos consistentes
const createIcon = (IconComponent: React.ComponentType<any>, color: string) => 
    React.createElement(IconComponent, { className: `w-12 h-12 ${color}` });

export const STRATEGIES_DATA: Strategy[] = [
    { id: 1, category: "supervivencia", title: "Sentirse Perdido", vivencias: ["Sentirse abandonado en la guardería o el colegio.", "Una mudanza repentina que lo aleja de sus amigos y su entorno conocido.", "El nacimiento de un hermano, sintiendo que ha perdido su lugar.", "Perderse en un lugar público (supermercado, centro comercial).", 'Sentir que no encaja en la familia o que "nadie me entiende".'], manifestacion: 'El niño parece **desorientado**, "en su propio mundo". Le cuesta seguir indicaciones, se distrae fácilmente y parece no escuchar.', icon: createIcon(Compass, "text-blue-600") },
    { id: 2, category: "supervivencia", title: "El Pequeño Cuidador", vivencias: ["Ver a uno de sus padres enfermo o triste y sentir que debe cuidarlo.", "Preocupación por las peleas constantes entre sus padres.", "Tener un hermano menor y sentir una responsabilidad desmedida por su bienestar.", "La muerte de una mascota, sintiendo que no la protegió lo suficiente."], manifestacion: 'Asume un rol de cuidador con sus hermanos, mascotas o incluso con sus propios padres. **Se preocupa excesivamente por el bienestar de los demás**.', icon: createIcon(Heart, "text-red-500") },
    { id: 3, category: "supervivencia", title: "El Muro Emocional", vivencias: ["Sufrir bullying o acoso escolar de forma continuada.", "Vivir en un ambiente familiar con gritos, críticas constantes o desprecio.", "Ser ridiculizado por un profesor o familiar delante de otros.", "Sentir su espacio personal invadido físicamente."], manifestacion: '**Aplanamiento emocional**. El niño se aísla, no expresa sus sentimientos, parece que "nada le importa" y se muestra frío o distante.', icon: createIcon(Square, "text-gray-600") },
    { id: 4, category: "corteza", title: "No Soy Suficiente", vivencias: ['Comparaciones constantes con hermanos o compañeros ("Tu hermano saca mejores notas").', "Sentir que no cumple las expectativas de sus padres en el deporte o en la escuela.", "Ser siempre el último en ser elegido para los juegos en equipo.", 'Una discapacidad física o dificultad de aprendizaje que lo hace sentirse "menos" que los demás.'], manifestacion: 'Para ocultar su inseguridad, el niño puede volverse **presumido, jactancioso o necesitar ser siempre el centro de atención**.', icon: createIcon(Trophy, "text-yellow-500") },
    { id: 5, category: "corteza", title: "Déficit de Atención", vivencias: ["Divorcio de los padres y extrañar al progenitor que ya no vive en casa.", "Padres ausentes por exceso de trabajo.", 'Sentirse "asfixiado" por padres sobreprotectores que no le dan espacio.', "Tener que compartir habitación con un hermano que no respeta sus cosas."], manifestacion: '**Mala memoria a corto plazo**. Es el niño "despistado" que olvida lo que se le acaba de decir, se distrae con todo y puede ser diagnosticado con **TDA o TDAH**.', icon: createIcon(Zap, "text-purple-500") },
    { id: 6, category: "corteza", title: "Amnesia por Dolor", vivencias: ["La muerte repentina de un familiar muy cercano o una mascota querida.", "Ser testigo de un accidente o un evento violento.", "Un proceso de divorcio muy conflictivo y traumático."], manifestacion: 'Problemas de memoria más severos, puede parecer **"desconectado" de la realidad**.', icon: createIcon(Cloud, "text-gray-400") },
    { id: 7, category: "corteza", title: "Miedo al Futuro", vivencias: ["Pánico ante un examen importante o una presentación en clase.", "Angustia por un cambio de colegio inminente.", "Miedo a una intervención médica o a una visita al dentista.", "Temor a que sus padres se separen."], manifestacion: '**Ansiedad constante**, preocupación excesiva por el futuro, miedos irracionales.', icon: createIcon(Frown, "text-orange-500") },
    { id: 8, category: "corteza", title: "Atrapado sin Salida", vivencias: ["Ser inmovilizado por otro niño durante una pelea sin poder defenderse.", "Ser obligado a comer algo que le da asco.", "Sentirse atrapado durante una discusión familiar sin poder irse.", "Quedarse encerrado accidentalmente en una habitación."], manifestacion: '**Tics nerviosos**, parpadeo constante, movimientos repetitivos de manos o pies, hiperactividad motora sin un propósito claro.', icon: createIcon(Activity, "text-green-600") },
    { id: 9, category: "territorial", title: "El Subibaja Emocional", vivencias: ['Conflicto de lealtades en un divorcio ("¿con quién estoy?").', "Sentirse el rey en casa de la abuela, pero un don nadie en el colegio.", "Peleas por juguetes o por el espacio con un hermano (conflicto territorial)."], manifestacion: '**Cambios de humor extremos**. Pasa de estar eufórico, muy hablador y activo (**manía**) a estar triste, apático y sin energía (**depresión**). Puede observarse un retraso en la madurez.', icon: createIcon(Theater, "text-pink-500") },
    { id: 10, category: "territorial", title: "Miedo en mi Territorio", vivencias: ["Miedo a que un ladrón entre en casa por la noche.", "Tener pánico a un profesor o a un compañero de clase que lo intimida.", "Sentir una amenaza constante por las discusiones de sus padres."], manifestacion: '**Crisis asmáticas**, dificultad para respirar.', icon: createIcon(FrownIcon, "text-red-600") },
    { id: 11, category: "territorial", title: "El Niño en las Nubes", vivencias: ["Un susto muy grande (un perro que le ladra de cerca, un accidente de coche).", "Sentir un miedo paralizante en una situación escolar o familiar."], manifestacion: '**El niño parece ausente, desconectado de la realidad**. Vive en un mundo de fantasía y le cuesta "aterrizar".', icon: createIcon(CloudIcon, "text-blue-400") },
    { id: 12, category: "territorial", title: "La Furia o la Autolesión", vivencias: ["Ser castigado injustamente por algo que hizo un hermano.", "Que le quiten su juguete preferido o le rompan algo valioso.", "Sentir una profunda frustración por no poder expresar su enojo o contrariedad."], manifestacion: 'En fase maníaca, **rabietas explosivas, agresividad física** (pega, muerde, destruye objetos). En fase depresiva, **la agresión se dirige hacia sí mismo** (se golpea, se araña, se muerde).', icon: createIcon(Angry, "text-red-700") },
    { id: 13, category: "territorial", title: "Haciendo Mío el Espacio", vivencias: ['La llegada de un nuevo bebé que "ocupa su lugar".', "Un nuevo compañero de cuarto o la llegada de un familiar a vivir en casa.", "Sentir que su espacio en el aula es invadido por otros niños."], manifestacion: '**Enuresis** (hacerse pipí en la cama o de día) de forma repetitiva y compulsiva.', icon: createIcon(Droplets, "text-blue-500") },
    { id: 14, category: "territorial", title: "El Creador de Historias", vivencias: ["No saber cuál es su rol en una familia reconstituida (padrastro, hermanastros).", "Miedo a ser castigado, por lo que inventa una realidad alternativa."], manifestacion: '**Inventa historias y se las cree**, exagera constantemente, miente patológicamente. Es el niño "fantasioso" o "cuentista".', icon: createIcon(MessageSquare, "text-indigo-500") },
    { id: 15, category: "territorial", title: "Encerrado en mi Mundo", vivencias: ["Exposición a múltiples traumas o un ambiente caótico y amenazante de forma prolongada.", "Combinación de conflictos graves de abandono, agresión e invasión del territorio."], manifestacion: '**Aislamiento profundo**. El niño se retira del mundo exterior, evita el contacto social y visual, y se refugia en su propia realidad.', icon: createIcon(DoorOpen, "text-gray-700") },
    { id: 16, category: "territorial", title: "El Conflicto en el Plato", vivencias: ['Una profunda contrariedad familiar que "no puede tragar".', "Sentir asco o repugnancia hacia una situación o persona en su entorno.", "Conflictos de identidad y de no poder decidir o tomar su propio camino."], manifestacion: '**Rechazo a la comida (anorexia) o ciclos de comer compulsivamente y vomitar (bulimia)**.', icon: createIcon(Utensils, "text-orange-600") },
    { id: 17, category: "otras", title: "Miedo en la Nuca", vivencias: ["Tener un miedo atroz a la oscuridad, a los monstruos o a estar solo.", "Sentir que alguien lo vigila o lo va a atacar por la espalda.", "Haber visto algo que lo aterrorizó y que no puede quitarse de la cabeza."], manifestacion: '**Paranoia, manía de persecución**, dice "ver cosas" que no están ahí.', icon: createIcon(Ghost, "text-purple-600") },
    { id: 18, category: "otras", title: "No Quiero Escuchar", vivencias: ["Estar expuesto diariamente a los gritos y peleas de sus padres.", "Recibir críticas, burlas o insultos de forma constante.", "Escuchar algo que le fue prohibido o un secreto familiar impactante."], manifestacion: '**Alucinaciones auditivas ("escucha voces")** o zumbidos en los oídos (tinnitus).', icon: createIcon(VolumeX, "text-red-500") },
    { id: 19, category: "otras", title: "Rituales para Controlar", vivencias: ["Un evento repentino y aterrador (susto) combinado con la sensación de injusticia y de no saber quién es o cuál es su lugar."], manifestacion: '**Necesidad de realizar rituales y manías** para sentir seguridad (lavarse las manos muchas veces, ordenar los juguetes de una forma específica, pisar ciertas baldosas).', icon: createIcon(RotateCcw, "text-cyan-600") },
    { id: 20, category: "otras", title: "Apagado por Sobrecarga", vivencias: ["Sentirse en una situación familiar o escolar totalmente desesperada y sin escapatoria.", "Un abuso continuado del que siente que no puede hablar ni huir."], manifestacion: 'El niño se "apaga", se queda inmóvil, sin energía, en un estado de postración. Puede haber una **pérdida de peso rápida e inexplicable**.', icon: createIcon(Power, "text-gray-500") }
];

export const FILTERS: Filter[] = [
    { key: 'all', label: 'Todas' },
    { key: 'supervivencia', label: 'Supervivencia y Protección' },
    { key: 'corteza', label: 'Sustancia Blanca y Corteza' },
    { key: 'territorial', label: 'Corteza Territorial' },
    { key: 'otras', label: 'Otras Estrategias' }
];